# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  # - "build"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "bahmutov/cypress-codefresh-example"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  # build:
  #   title: "Building Docker image"
  #   type: "build"
  #   image_name: "bahmutov/cypress-codefresh-example"
  #   working_directory: "${{clone}}"
  #   tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
  #   # If you have a Dockerfile in the repo you can use
  #   # dockerfile: 'Dockerfile'
  #   dockerfile:
  #     content: "FROM node:10.13.0-alpine\n          WORKDIR /root/onboarding\n          COPY . /\n          CMD npm start"
  #   stage: "build"

  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: "cypress/base:12.19.0" # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - "npm ci"
      - "npx cypress verify"
      - "npx cypress info"
    stage: "test"

